import 'package:flutter/material.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/GeneratedLabelWidget34.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/Generated1TopARegularaFlatWidget5.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/Generated1ImagetopAElevatedaRestingWidget5.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/Generated1ImagetopAElevatedaRestingWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/Generated1ImagetopAElevatedaRestingWidget7.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/GeneratedAppbar1TopAStandardaStandardWidget5.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid4widget/generated/Generated1ImagetopAElevatedaRestingWidget4.dart';

/* Frame Android - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4666666666666667;

                  final double height = constraints.maxHeight * 0.3828125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.016666666666666666,
                        y: constraints.maxHeight * 0.196875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1ImagetopAElevatedaRestingWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.45555555555555555;

                  final double height = constraints.maxHeight * 0.340625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5055555555555555,
                        y: constraints.maxHeight * 0.5640625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1ImagetopAElevatedaRestingWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4666666666666667;

                  final double height = constraints.maxHeight * 0.3828125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.005555555555555556,
                        y: constraints.maxHeight * 0.5484375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1ImagetopAElevatedaRestingWidget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4666666666666667;

                  final double height = constraints.maxHeight * 0.3828125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5055555555555555,
                        y: constraints.maxHeight * 0.23125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1ImagetopAElevatedaRestingWidget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2111111111111111;

                  final double height = constraints.maxHeight * 0.059375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6944444444444444,
                        y: constraints.maxHeight * 0.93125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedLabelWidget34(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0027777777777778;

                  final double height = constraints.maxHeight * 0.1390625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.002777777777777778,
                        y: constraints.maxHeight * 0.0390625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1TopARegularaFlatWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0027777777777778;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.0015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppbar1TopAStandardaStandardWidget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
