import 'package:flutter/material.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/Generated1ButtonWidget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/GeneratedContentWidget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/Generated1ImagetopAElevatedaRestingWidget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/Generated1TopARegularaFlatWidget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/GeneratedAppbar1TopAStandardaStandardWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid3widget/generated/Generated2FourupAOnPrimaryWidget.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 3.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 185.0,
                child: GeneratedContentWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 175.0,
                child: Generated1ImagetopAElevatedaRestingWidget1(),
              ),
              Positioned(
                left: 143.0,
                top: null,
                right: null,
                bottom: 54.0,
                width: 75.0,
                height: 36.0,
                child: Generated1ButtonWidget1(),
              ),
              Positioned(
                left: -1.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 56.0,
                child: Generated1TopARegularaFlatWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0027777777777778;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.002777777777777778,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppbar1TopAStandardaStandardWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.0875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.005555555555555556,
                        y: constraints.maxHeight * 0.9125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated2FourupAOnPrimaryWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
