import 'package:flutter/material.dart';

/* Frame App bar /1. Top /A. Standard/a. Standard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppbar1TopAStandardaStandardWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 361.0,
      height: 24.0,
    ));
  }
}
