import 'package:flutter/material.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedAppbar1TopAStandardaStandardWidget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/Generated1TopARegularaFlatWidget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedH5Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedCFocusedWidget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedLapersistenciadelamemoriaSD1Widget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedH4Widget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/Generated3ContainedBTextIconEnabledWidget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedCFocusedWidget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid1widget/generated/GeneratedFrame1Widget.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 11.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 213.0,
                child: GeneratedLapersistenciadelamemoriaSD1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.044444444444444446,
                        y: constraints.maxHeight * 0.4765625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.044444444444444446,
                        y: constraints.maxHeight * 0.6359375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.40555555555555556;

                  final double height = constraints.maxHeight * 0.05625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2972222222222222,
                        y: constraints.maxHeight * 0.8125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated3ContainedBTextIconEnabledWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 124.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 36.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.55;

                  final double height = constraints.maxHeight * 0.059375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.22777777777777777,
                        y: constraints.maxHeight * 0.1578125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedH4Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.34444444444444444;

                  final double height = constraints.maxHeight * 0.0453125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.31666666666666665,
                        y: constraints.maxHeight * 0.253125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedH5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -1.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 34.0,
                child: Generated1TopARegularaFlatWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0333333333333334;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.019444444444444445,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppbar1TopAStandardaStandardWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
