import 'package:flutter/material.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/Generated1ImagetopAElevatedaRestingWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/GeneratedAppbar1TopAStandardaStandardWidget3.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/Generated1TopARegularaFlatWidget3.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/GeneratedContentWidget2.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/Generated1ImagetopAElevatedaRestingWidget2.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/GeneratedContentWidget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/Generated2FourupAOnPrimaryWidget2.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid6widget/generated/GeneratedButtonsWidget1.dart';

/* Frame Android - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 41.0,
                child: GeneratedContentWidget1(),
              ),
              Positioned(
                left: 2.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 36.0,
                child: GeneratedContentWidget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 358.0,
                height: 44.0,
                child: TransformHelper.translate(
                    x: -1.00,
                    y: 241.00,
                    z: 0,
                    child: GeneratedButtonsWidget1()),
              ),
              Positioned(
                left: 1.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 191.0,
                child: Generated1ImagetopAElevatedaRestingWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 317.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 191.0,
                child: Generated1ImagetopAElevatedaRestingWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0027777777777778;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.0015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppbar1TopAStandardaStandardWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 56.0,
                child: Generated1TopARegularaFlatWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.0875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.002777777777777778,
                        y: constraints.maxHeight * 0.9109375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated2FourupAOnPrimaryWidget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
