import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/GeneratedNoticias31Widget.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/Generated1TopARegularaFlatWidget6.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/GeneratedHeaderWidget28.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/GeneratedSystembarWidget6.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/GeneratedHeaderWidget27.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/GeneratedHeaderWidget26.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid7widget/generated/Generated2FourupAOnPrimaryWidget3.dart';

/* Frame Android - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 2.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 90.0,
                child: GeneratedHeaderWidget26(),
              ),
              Positioned(
                left: 105.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 26.0,
                child: GeneratedHeaderWidget27(),
              ),
              Positioned(
                left: 135.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 50.0,
                child: GeneratedHeaderWidget28(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.0875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated2FourupAOnPrimaryWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -1.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 56.0,
                child: Generated1TopARegularaFlatWidget6(),
              ),
              Positioned(
                left: null,
                top: 0.0,
                right: null,
                bottom: 0.0,
                width: 361.0,
                height: null,
                child: TransformHelper.translate(
                    x: -0.50,
                    y: 0.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double height = constraints.maxHeight * 0.0375;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: 0,
                            y: 0,
                            z: 0,
                            child: Container(
                              height: height,
                              child: GeneratedSystembarWidget6(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 11.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 338.0,
                height: 214.0,
                child: GeneratedNoticias31Widget(),
              )
            ]),
      ),
    ));
  }
}
