import 'package:flutter/material.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/Generated3ContainedBTextIconEnabledWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedCFocusedWidget3.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedCFocusedWidget5.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedH4Widget1.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedAppbar1TopAStandardaStandardWidget4.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedCFocusedWidget4.dart';
import 'package:flutterapp/links_20newsapp/generatedandroid2widget/generated/GeneratedCFocusedWidget2.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05,
                        y: constraints.maxHeight * 0.2828125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05,
                        y: constraints.maxHeight * 0.41875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.044444444444444446,
                        y: constraints.maxHeight * 0.565625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9111111111111111;

                  final double height = constraints.maxHeight * 0.1125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05,
                        y: constraints.maxHeight * 0.7015625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedCFocusedWidget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3111111111111111;

                  final double height = constraints.maxHeight * 0.05625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.35555555555555557,
                        y: constraints.maxHeight * 0.8609375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated3ContainedBTextIconEnabledWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0333333333333334;

                  final double height = constraints.maxHeight * 0.08125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.03333333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedAppbar1TopAStandardaStandardWidget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.44166666666666665;

                  final double height = constraints.maxHeight * 0.0640625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.26944444444444443,
                        y: constraints.maxHeight * 0.1484375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedH4Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
